[package]
name = "shapes-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
shacl_validation = "0.1.7"
srdf = "0.1.7"
clap = { version = "4.2.1", features = ["derive"] }
memory-stats = "1.2.0"
csv = "1.3.0"
statistical = "1.0.0"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "thin"