[package]
name = "shapes-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
shacl_validation = { git = "https://github.com/weso/shapes-rs.git" }
clap = { version = "4.2.1", features = ["derive"] }
memory-stats = "1.2.0"